-- CreateTable
CREATE TABLE "Pengajuan" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "tanggal" DATETIME NOT NULL,
    "waktu" TEXT NOT NULL,
    "lokasiKerja" TEXT NOT NULL,
    "departemenId" INTEGER NOT NULL,
    "judulPekerjaan" TEXT NOT NULL,
    "nomorIzinKerja" TEXT NOT NULL,
    "pemegangIjinId" INTEGER NOT NULL,
    "jabatanId" INTEGER NOT NULL,
    "perusahaanId" INTEGER NOT NULL,
    "jenisPekerjaanId" INTEGER NOT NULL,
    "keterangan" TEXT,
    "petugasPemeriksaId" INTEGER NOT NULL,
    "pengawasPekerjaanId" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Pengajuan_departemenId_fkey" FOREIGN KEY ("departemenId") REFERENCES "Departemen" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Pengajuan_pemegangIjinId_fkey" FOREIGN KEY ("pemegangIjinId") REFERENCES "Karyawan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Pengajuan_jabatanId_fkey" FOREIGN KEY ("jabatanId") REFERENCES "Jabatan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Pengajuan_perusahaanId_fkey" FOREIGN KEY ("perusahaanId") REFERENCES "Perusahaan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Pengajuan_jenisPekerjaanId_fkey" FOREIGN KEY ("jenisPekerjaanId") REFERENCES "JenisPekerjaan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Pengajuan_petugasPemeriksaId_fkey" FOREIGN KEY ("petugasPemeriksaId") REFERENCES "Karyawan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Pengajuan_pengawasPekerjaanId_fkey" FOREIGN KEY ("pengawasPekerjaanId") REFERENCES "Karyawan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
